// src/constants/data.js

export const districts = [
  "Ariyalur",
  "Chengalpet",
  "Chennai Corporation",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kanchipuram",
  "Kanniyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Perambalur",
  "Pudukkottai",
  "Ramanadhapuram",
  "Ranipet",
  "Sivagangai",
  "Tenkasi",
  "Thanjavur",
  "The Nilgiris",
  "Theni",
  "Thirupathur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Tuticorin",
  "Vellore",
  "Villupuram",
];

export const industries = [
  "Textiles",
  "Automobile",
  "IT",
  "Food Processing",
  "Chemicals",
  "Flour / Huller Mills (Below 12 Kw)",
  "Floriculture",
  "Micro Enterprises",
  "Cottage And Tiny Industries",
  "Horticulture (Below 12 Kw)",
  "Poultry/Bird Farming",
  "Common Effluent Treatment Plants (Below 12 Kw)",
  "Fish/Prawn Culture",
  "Sericulture",
  "Ice Factory (Below 12 Kw)",
  "Cattle Farming",
  "Gem And Diamond Cutting Units",
  "Pumping Of Water For The Purpose Of Agriculture And Allied Activities",
  "Saw Mill (Below 12 Kw)",
  "Rice Mills (Below 12 Kw)",
  "Coffee Roasting And Grinding Works (Below 12 Kw)",
  "Two Wheelers Show Room",
  "Mushroom Cultivation / Raising Installations",
  "Power Loom",
  "Other Industries",
  "Rice Mills (Above 12 Kw)",
  "Flour / Huller Mills (Above 12 Kw)",
  "Saw Mill (Above 12 Kw)",
  "Ice Cold Bevarages",
  "Chemical Industries",
  "Steel Industries",
  "Ice Factory (Above 12 Kw)",
  "Dairy Units (Above 12 Kw)",
  "Body Building Units (Below 12 Kw)",
  "Milk Dairies",
  "It Industries",
  "Battery Charging Units (Above 12 Kw)",
  "Plastic Industries",
  "Body Building Units (Above 12 Kw)",
  "Lime Crushing Industry",
  "Printing Presses",
  "Toy/Wood Industries",
  "Mineral Water Processing / Drinking Water Bottling Plants",
  "Libraries",
  "Dairy Units (Below 12 Kw)",
  "Domestic - Residential/Own Use",
  "Poultry Farms (Above 12 Kw)",
  "Cold Storage Plants",
  "Common Effluent Treatment Plants (Above 12 Kw)",
  "Ironing",
  "Wet Grinders",
  "Bakery Product Manufacturing Units",
  "Textile Industries",
  "Coffee Roasting And Grinding Works (Above 12 Kw)",
  "Retirement Homes/Senior Citizen Homes/Old Age Homes",
  "Bulk Milk Vending Booths",
  "Drug Manufacturing Units And Testing Laboratories",
  "Green House",
  "Ironing / Laundry Works",
  "Tanneries",
  "Advocate/Auditor/Doctors Consulting Or Office Consultant Rooms Beyound 200 Sqft. Attached To The Residence Of Such Professionals",
  "Waste Land Development",
  "Prawn Farming (Above 12 Kw)",
  "Heating And Motive Power (I/C Lighting; Installations Of Industrial Units)",
  "Saggo Factories",
  "Carbide Industries",
  "Garment Manufacturing Units",
  "Data Centres",
  "Private Solid Waste Processing Plants",
  "Gold / Silver Ornament Manufacturing Units",
  "Four Wheelers Show Room",
  "Supply For Construction Of New Building",
  "Twisting",
  "Piggery Farms",
  "Cardamom Drying",
  "Sugarcane Crushers",
  "Petty Shops/Kiosks/Tea Shops",
  "Advocate Office/Auditors Office/Consultant Office",
  "Hostel",
  "Saloons/Beauty Parlours",
  "Destitute Home",
  "Commercial Built Up Area <25% For Common Lighting, Water Supply, Lift In Multi-Storied Buildings/Residential Complexes",
  "Battery Charging Units (Below 12 Kw)",
  "Milk Society/Milk Booth/Aavin Milk Parlour",
  "Brided Cord Manufacture",
  "Warping",
  "Actual Places Of Worship",
  "Winding",
  "Bulk Ice Cream And Ice Manufacturing Units",
  "Textile Stores",
  "Hybrid Seed Processing Units",
  "Others",
  "Restaurants/Small Hotels/Big Hotels",
  "Biotech Labs",
  "Companies Corporate Offices",
  "Silk / Cotton Colour Dying",
  "Supply For Temporary Activities Other Than Construction Of Building",
  "Creches",
  "Laboratories",
  "Sweets And Bakery Shops",
  "Textile Showroom/Connected Godown/Tailoring Shop",
  "Road/Pathways Leading To The Temples",
  "Village Panchayats Water Works",
  "Additional Construction Exceeding 2000 Sq.Ft",
  "Shopping Mall/Complexes",
  "Water Supply Agencies/Agents",
  "Public Ev Charging Stations (Pcs)",
  "Grinding Shops",
  "Satellite Communication Centres",
  "Handloom",
  "Common Lighting, Water Supply, Lift In Multi-Stories Building/Residential Complexes Having Non-Residential Built Up Area More Than 25% Of The Total Built Up Area",
  "Provision Stores/Groceries Shops",
  "Domestic/Appartment",
  "Agarbathi Manufacturing Units",
];
